name: Demo
on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Execute tests
        run: |
          echo "Hello world"
      - name: Execute tests
        run: |
          echo "Hello world"
      - name: Execute tests
        run: |
          echo "Hello world"
